-- H2 schema for tests. Mirrors the Postgres Flyway migrations but uses portable
-- syntax (PRIMARY KEY declared at the table level so H2 accepts column defaults;
-- functional indexes substituted for plain UNIQUE constraints).
DROP TABLE IF EXISTS change_log;
DROP TABLE IF EXISTS sdlc_phases;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE users (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    first_name     VARCHAR(100) NOT NULL,
    last_name      VARCHAR(100) NOT NULL,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_email_uq UNIQUE (email)
);

CREATE TABLE roles (
    id     SMALLINT     NOT NULL,
    name   VARCHAR(64)  NOT NULL UNIQUE,
    CONSTRAINT roles_pk PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    user_id  BIGINT   NOT NULL,
    role_id  SMALLINT NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE teams (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  BIGINT       NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT       NOT NULL,
    CONSTRAINT teams_pk PRIMARY KEY (id),
    CONSTRAINT teams_name_uq UNIQUE (name),
    CONSTRAINT teams_created_by_fk FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT teams_updated_by_fk FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE TABLE sdlc_phases (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    display_order INTEGER      NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT       NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT       NOT NULL,
    CONSTRAINT sdlc_phases_pk PRIMARY KEY (id),
    CONSTRAINT sdlc_phases_name_uq UNIQUE (name),
    CONSTRAINT sdlc_phases_display_order_uq UNIQUE (display_order),
    CONSTRAINT sdlc_phases_created_by_fk FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT sdlc_phases_updated_by_fk FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE TABLE change_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(64)  NOT NULL,
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(32)  NOT NULL,
    field_name  VARCHAR(128),
    old_value   TEXT,
    new_value   TEXT,
    changed_by  BIGINT       NOT NULL,
    changed_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source      VARCHAR(32)  NOT NULL DEFAULT 'WEB',
    notes       TEXT,
    CONSTRAINT change_log_pk PRIMARY KEY (id),
    CONSTRAINT change_log_changed_by_fk FOREIGN KEY (changed_by) REFERENCES users (id)
);
