-- H2 schema for tests. Mirrors the Postgres Flyway migrations but uses portable
-- syntax (PRIMARY KEY at the table level so H2 accepts column defaults;
-- functional indexes substituted for plain UNIQUE constraints).
--
-- Audit FKs are intentionally NOT declared here so user hard-deletes don't
-- trip referential integrity in tests — same posture as V6 in production.
DROP TABLE IF EXISTS invitation_tokens;
DROP TABLE IF EXISTS blended_rates;
DROP TABLE IF EXISTS change_log;
DROP TABLE IF EXISTS sdlc_phases;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE users (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email                    VARCHAR(255) NOT NULL,
    password_hash            VARCHAR(100) NOT NULL,
    first_name               VARCHAR(100) NOT NULL,
    last_name                VARCHAR(100) NOT NULL,
    active                   BOOLEAN      NOT NULL DEFAULT TRUE,
    invitation_status        VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    invited_by               BIGINT,
    invited_at               TIMESTAMP WITH TIME ZONE,
    invitation_expires_at    TIMESTAMP WITH TIME ZONE,
    invitation_accepted_at   TIMESTAMP WITH TIME ZONE,
    last_active_at           TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_email_uq UNIQUE (email),
    CONSTRAINT users_status_chk CHECK (invitation_status IN ('ACTIVE', 'PENDING_INVITE', 'INACTIVE'))
);

CREATE TABLE roles (
    id     SMALLINT     NOT NULL,
    name   VARCHAR(64)  NOT NULL UNIQUE,
    CONSTRAINT roles_pk PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    user_id  BIGINT   NOT NULL,
    role_id  SMALLINT NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE teams (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  BIGINT       NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT       NOT NULL,
    CONSTRAINT teams_pk PRIMARY KEY (id),
    CONSTRAINT teams_name_uq UNIQUE (name)
);

CREATE TABLE sdlc_phases (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    display_order INTEGER      NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT       NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT       NOT NULL,
    CONSTRAINT sdlc_phases_pk PRIMARY KEY (id),
    CONSTRAINT sdlc_phases_name_uq UNIQUE (name),
    CONSTRAINT sdlc_phases_display_order_uq UNIQUE (display_order)
);

CREATE TABLE change_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(64)  NOT NULL,
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(32)  NOT NULL,
    field_name  VARCHAR(128),
    old_value   TEXT,
    new_value   TEXT,
    changed_by  BIGINT       NOT NULL,
    changed_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source      VARCHAR(32)  NOT NULL DEFAULT 'WEB',
    notes       TEXT,
    CONSTRAINT change_log_pk PRIMARY KEY (id)
);

CREATE TABLE blended_rates (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    onshore_rate    NUMERIC(10,2)  NOT NULL CHECK (onshore_rate > 0),
    offshore_rate   NUMERIC(10,2)  NOT NULL CHECK (offshore_rate > 0),
    effective_date  DATE           NOT NULL,
    note            TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT         NOT NULL,
    CONSTRAINT blended_rates_pk PRIMARY KEY (id),
    CONSTRAINT blended_rates_creator_fk FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE invitation_tokens (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    token       VARCHAR(64)    NOT NULL UNIQUE,
    user_id     BIGINT         NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    revoked_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT invitation_tokens_pk PRIMARY KEY (id),
    CONSTRAINT invitation_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
