-- H2 schema for tests. Mirrors the Postgres Flyway migrations but uses portable
-- syntax (PRIMARY KEY at the table level so H2 accepts column defaults;
-- functional indexes substituted for plain UNIQUE constraints).
--
-- Audit FKs are intentionally NOT declared here so user hard-deletes don't
-- trip referential integrity in tests — same posture as V6 in production.
DROP TABLE IF EXISTS estimate_request_question_answers;
DROP TABLE IF EXISTS estimate_request_phase_lines;
DROP TABLE IF EXISTS estimate_request_items;
DROP TABLE IF EXISTS estimate_requests;
DROP TABLE IF EXISTS estimate_template_lines;
DROP TABLE IF EXISTS estimate_templates;
DROP TABLE IF EXISTS critical_questions;
DROP TABLE IF EXISTS sub_features;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS user_teams;
DROP TABLE IF EXISTS invitation_tokens;
DROP TABLE IF EXISTS blended_rates;
DROP TABLE IF EXISTS change_log;
DROP TABLE IF EXISTS sdlc_phases;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE users (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email                    VARCHAR(255) NOT NULL,
    password_hash            VARCHAR(100) NOT NULL,
    first_name               VARCHAR(100) NOT NULL,
    last_name                VARCHAR(100) NOT NULL,
    active                   BOOLEAN      NOT NULL DEFAULT TRUE,
    invitation_status        VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    invited_by               BIGINT,
    invited_at               TIMESTAMP WITH TIME ZONE,
    invitation_expires_at    TIMESTAMP WITH TIME ZONE,
    invitation_accepted_at   TIMESTAMP WITH TIME ZONE,
    last_active_at           TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_email_uq UNIQUE (email),
    CONSTRAINT users_status_chk CHECK (invitation_status IN ('ACTIVE', 'PENDING_INVITE', 'INACTIVE'))
);

CREATE TABLE roles (
    id     SMALLINT     NOT NULL,
    name   VARCHAR(64)  NOT NULL UNIQUE,
    CONSTRAINT roles_pk PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    user_id  BIGINT   NOT NULL,
    role_id  SMALLINT NOT NULL,
    CONSTRAINT user_roles_pk PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE teams (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  BIGINT       NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT       NOT NULL,
    CONSTRAINT teams_pk PRIMARY KEY (id),
    CONSTRAINT teams_name_uq UNIQUE (name)
);

-- Phase 8: user_teams join table
CREATE TABLE user_teams (
    user_id  BIGINT NOT NULL,
    team_id  BIGINT NOT NULL,
    CONSTRAINT user_teams_pk PRIMARY KEY (user_id, team_id),
    CONSTRAINT user_teams_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_teams_team_fk FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE
);

CREATE TABLE sdlc_phases (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    display_order INTEGER      NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT       NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT       NOT NULL,
    CONSTRAINT sdlc_phases_pk PRIMARY KEY (id),
    CONSTRAINT sdlc_phases_name_uq UNIQUE (name),
    CONSTRAINT sdlc_phases_display_order_uq UNIQUE (display_order)
);

CREATE TABLE change_log (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(64)  NOT NULL,
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(32)  NOT NULL,
    field_name  VARCHAR(128),
    old_value   TEXT,
    new_value   TEXT,
    changed_by  BIGINT       NOT NULL,
    changed_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source      VARCHAR(32)  NOT NULL DEFAULT 'WEB',
    notes       TEXT,
    CONSTRAINT change_log_pk PRIMARY KEY (id)
);

CREATE TABLE blended_rates (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    onshore_rate    NUMERIC(10,2)  NOT NULL CHECK (onshore_rate > 0),
    offshore_rate   NUMERIC(10,2)  NOT NULL CHECK (offshore_rate > 0),
    effective_date  DATE           NOT NULL,
    note            TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT         NOT NULL,
    CONSTRAINT blended_rates_pk PRIMARY KEY (id),
    CONSTRAINT blended_rates_creator_fk FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE invitation_tokens (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    token       VARCHAR(64)    NOT NULL UNIQUE,
    user_id     BIGINT         NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    revoked_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT invitation_tokens_pk PRIMARY KEY (id),
    CONSTRAINT invitation_tokens_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ---- Phase 5a: products + sub_features + critical_questions -------------
-- See V8 migration for design rationale (partial-unique-on-active divergence,
-- XOR parent constraint on critical_questions, cascade-delete behaviour).

CREATE TABLE products (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    mode        VARCHAR(16)  NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    team_id     BIGINT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  BIGINT       NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT       NOT NULL,
    CONSTRAINT products_pk PRIMARY KEY (id),
    CONSTRAINT products_mode_chk CHECK (mode IN ('ATOMIC', 'CONTAINER')),
    CONSTRAINT products_team_fk FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE TABLE sub_features (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id  BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  BIGINT       NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by  BIGINT       NOT NULL,
    CONSTRAINT sub_features_pk PRIMARY KEY (id),
    CONSTRAINT sub_features_product_fk FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE critical_questions (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id     BIGINT,
    sub_feature_id BIGINT,
    question_text  TEXT         NOT NULL,
    help_text      TEXT,
    required       BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order  INTEGER      NOT NULL,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     BIGINT       NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by     BIGINT       NOT NULL,
    CONSTRAINT critical_questions_pk PRIMARY KEY (id),
    CONSTRAINT critical_questions_product_fk FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT critical_questions_sub_feature_fk FOREIGN KEY (sub_feature_id) REFERENCES sub_features (id) ON DELETE CASCADE,
    CONSTRAINT critical_questions_parent_xor_chk
        CHECK ((product_id IS NOT NULL) <> (sub_feature_id IS NOT NULL))
);

CREATE TABLE estimate_templates (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id     BIGINT,
    sub_feature_id BIGINT,
    version_number INTEGER      NOT NULL,
    is_active      BOOLEAN      NOT NULL,
    change_reason  TEXT,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     BIGINT       NOT NULL,
    CONSTRAINT estimate_templates_pk PRIMARY KEY (id),
    CONSTRAINT estimate_templates_product_fk FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT estimate_templates_sub_feature_fk FOREIGN KEY (sub_feature_id) REFERENCES sub_features (id) ON DELETE CASCADE,
    CONSTRAINT estimate_templates_parent_xor_chk
        CHECK ((product_id IS NOT NULL) <> (sub_feature_id IS NOT NULL))
);

CREATE TABLE estimate_template_lines (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    template_id   BIGINT        NOT NULL,
    sdlc_phase_id BIGINT        NOT NULL,
    -- Phase 5b: every cell required (V9 in Postgres). Mirrored here.
    onshore_low   NUMERIC(10,2) NOT NULL,
    onshore_med   NUMERIC(10,2) NOT NULL,
    onshore_high  NUMERIC(10,2) NOT NULL,
    offshore_low  NUMERIC(10,2) NOT NULL,
    offshore_med  NUMERIC(10,2) NOT NULL,
    offshore_high NUMERIC(10,2) NOT NULL,
    CONSTRAINT estimate_template_lines_pk PRIMARY KEY (id),
    CONSTRAINT estimate_template_lines_template_fk FOREIGN KEY (template_id) REFERENCES estimate_templates (id) ON DELETE CASCADE,
    CONSTRAINT estimate_template_lines_phase_fk FOREIGN KEY (sdlc_phase_id) REFERENCES sdlc_phases (id),
    CONSTRAINT estimate_template_lines_unique_phase_per_template UNIQUE (template_id, sdlc_phase_id)
);

-- ---- Phase 9a: estimate_requests (parent) + estimate_request_items (per-product) --
-- See V13 migration for design rationale. estimate_requests is now a thin
-- parent container; all per-product state lives in estimate_request_items.

CREATE TABLE estimate_requests (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    requester_id    BIGINT       NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT estimate_requests_pk PRIMARY KEY (id)
);

CREATE TABLE estimate_request_items (
    id                       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    estimate_request_id      BIGINT       NOT NULL,
    product_id               BIGINT       NOT NULL,
    sub_feature_id           BIGINT,
    template_id              BIGINT,
    status                   VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    complexity               VARCHAR(8),
    reviewer_id              BIGINT,
    justification            TEXT,
    submitted_at             TIMESTAMP WITH TIME ZONE,
    reviewed_at              TIMESTAMP WITH TIME ZONE,
    approved_blended_rate_id BIGINT,
    display_order            INTEGER      NOT NULL DEFAULT 0,
    -- Phase 9b: rejection/revision fields
    rejection_reason         TEXT,
    revision_count           INTEGER      NOT NULL DEFAULT 0,
    original_product_id      BIGINT,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT estimate_request_items_pk PRIMARY KEY (id),
    CONSTRAINT estimate_request_items_request_fk
        FOREIGN KEY (estimate_request_id) REFERENCES estimate_requests (id) ON DELETE CASCADE,
    CONSTRAINT estimate_request_items_product_fk
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT estimate_request_items_sub_feature_fk
        FOREIGN KEY (sub_feature_id) REFERENCES sub_features (id),
    CONSTRAINT estimate_request_items_template_fk
        FOREIGN KEY (template_id) REFERENCES estimate_templates (id),
    CONSTRAINT estimate_request_items_blended_rate_fk
        FOREIGN KEY (approved_blended_rate_id) REFERENCES blended_rates (id),
    CONSTRAINT estimate_request_items_status_chk
        CHECK (status IN ('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED')),
    CONSTRAINT estimate_request_items_complexity_chk
        CHECK (complexity IS NULL OR complexity IN ('LOW', 'MED', 'HIGH'))
);

CREATE TABLE estimate_request_phase_lines (
    id                                BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    estimate_request_item_id          BIGINT        NOT NULL,
    sdlc_phase_id                     BIGINT        NOT NULL,
    sdlc_phase_name_snapshot          VARCHAR(255)  NOT NULL,
    sdlc_phase_display_order_snapshot INTEGER       NOT NULL,
    onshore_low                       NUMERIC(10,2) NOT NULL,
    onshore_med                       NUMERIC(10,2) NOT NULL,
    onshore_high                      NUMERIC(10,2) NOT NULL,
    offshore_low                      NUMERIC(10,2) NOT NULL,
    offshore_med                      NUMERIC(10,2) NOT NULL,
    offshore_high                     NUMERIC(10,2) NOT NULL,
    onshore_override                  NUMERIC(10,2),
    offshore_override                 NUMERIC(10,2),
    CONSTRAINT estimate_request_phase_lines_pk PRIMARY KEY (id),
    CONSTRAINT estimate_request_phase_lines_item_fk
        FOREIGN KEY (estimate_request_item_id) REFERENCES estimate_request_items (id) ON DELETE CASCADE,
    CONSTRAINT estimate_request_phase_lines_phase_fk
        FOREIGN KEY (sdlc_phase_id) REFERENCES sdlc_phases (id),
    CONSTRAINT estimate_request_phase_lines_unique
        UNIQUE (estimate_request_item_id, sdlc_phase_id)
);

CREATE TABLE estimate_request_question_answers (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    estimate_request_item_id BIGINT NOT NULL,
    critical_question_id   BIGINT NOT NULL,
    question_text_snapshot TEXT   NOT NULL,
    answer_text            TEXT   NOT NULL,
    CONSTRAINT estimate_request_question_answers_pk PRIMARY KEY (id),
    CONSTRAINT estimate_request_question_answers_item_fk
        FOREIGN KEY (estimate_request_item_id) REFERENCES estimate_request_items (id) ON DELETE CASCADE,
    CONSTRAINT estimate_request_question_answers_question_fk
        FOREIGN KEY (critical_question_id) REFERENCES critical_questions (id),
    CONSTRAINT estimate_request_question_answers_unique
        UNIQUE (estimate_request_item_id, critical_question_id)
);
